# Copyright (c) 2023 Joseph Hale
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---  # Denotes the start of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395
name: HideAndSeek
main: dev.restonic4.hide_and_seek.HideAndSeekPlugin
version: 0.1.0
api-version: 1.19
commands:
  hs:
    description: Main command for Hide and Seek.
    permission: hideandseek.admin
    usage: /hs <subcommand>
... # Denotes the end of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395